services:
    web:
        expose:
            - 9997
            - 9998
            - 9999
        environment:
            - HOST=0.0.0.0
            - PORT=9997
            - APP_URL=http://${DDEV_SITENAME}.ddev.site
            - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,9999:9999,9998:9998,9997:9997
            - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,8899:9999,8888:9998,8887:9997
